<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-J35S6C5" failures="1" tests="1" name="Default test" time="9.085" errors="0" timestamp="2023-10-05T22:27:42 IST">
  <testcase classname="timeout.com.TimeOutClass" name="timeOutTestCase1" time="9.028">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method timeout.com.TimeOutClass.timeOutTestCase1() didn&amp;apos;t finish within the time-out 9000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method timeout.com.TimeOutClass.timeOutTestCase1() didn't finish within the time-out 9000
at java.base@11.0.16.1/java.lang.Thread.sleep(Native Method)
at app//timeout.com.TimeOutClass.timeOutTestCase1(TimeOutClass.java:9)
at java.base@11.0.16.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@11.0.16.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base@11.0.16.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@11.0.16.1/java.lang.reflect.Method.invoke(Method.java:566)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@11.0.16.1/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.16.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.16.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.16.1/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- timeOutTestCase1 -->
</testsuite> <!-- Default test -->
